//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandidatosWSDL.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servidor.com/", ConfigurationName="ServiceReference1.Conector")]
    public interface Conector {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento claveElectoral del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://servidor.com/Conector/insertarCandidatoRequest", ReplyAction="http://servidor.com/Conector/insertarCandidatoResponse")]
        CandidatosWSDL.ServiceReference1.insertarCandidatoResponse insertarCandidato(CandidatosWSDL.ServiceReference1.insertarCandidatoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servidor.com/Conector/insertarCandidatoRequest", ReplyAction="http://servidor.com/Conector/insertarCandidatoResponse")]
        System.Threading.Tasks.Task<CandidatosWSDL.ServiceReference1.insertarCandidatoResponse> insertarCandidatoAsync(CandidatosWSDL.ServiceReference1.insertarCandidatoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://servidor.com/Conector/mostrarCandidatosRequest", ReplyAction="http://servidor.com/Conector/mostrarCandidatosResponse")]
        CandidatosWSDL.ServiceReference1.mostrarCandidatosResponse mostrarCandidatos(CandidatosWSDL.ServiceReference1.mostrarCandidatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servidor.com/Conector/mostrarCandidatosRequest", ReplyAction="http://servidor.com/Conector/mostrarCandidatosResponse")]
        System.Threading.Tasks.Task<CandidatosWSDL.ServiceReference1.mostrarCandidatosResponse> mostrarCandidatosAsync(CandidatosWSDL.ServiceReference1.mostrarCandidatosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombreCiudadano del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://servidor.com/Conector/insertarCiudadanoRequest", ReplyAction="http://servidor.com/Conector/insertarCiudadanoResponse")]
        CandidatosWSDL.ServiceReference1.insertarCiudadanoResponse insertarCiudadano(CandidatosWSDL.ServiceReference1.insertarCiudadanoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servidor.com/Conector/insertarCiudadanoRequest", ReplyAction="http://servidor.com/Conector/insertarCiudadanoResponse")]
        System.Threading.Tasks.Task<CandidatosWSDL.ServiceReference1.insertarCiudadanoResponse> insertarCiudadanoAsync(CandidatosWSDL.ServiceReference1.insertarCiudadanoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento claveElectoral del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://servidor.com/Conector/candidatosRequest", ReplyAction="http://servidor.com/Conector/candidatosResponse")]
        CandidatosWSDL.ServiceReference1.candidatosResponse candidatos(CandidatosWSDL.ServiceReference1.candidatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servidor.com/Conector/candidatosRequest", ReplyAction="http://servidor.com/Conector/candidatosResponse")]
        System.Threading.Tasks.Task<CandidatosWSDL.ServiceReference1.candidatosResponse> candidatosAsync(CandidatosWSDL.ServiceReference1.candidatosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento partido del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://servidor.com/Conector/modificarCandidatoRequest", ReplyAction="http://servidor.com/Conector/modificarCandidatoResponse")]
        CandidatosWSDL.ServiceReference1.modificarCandidatoResponse modificarCandidato(CandidatosWSDL.ServiceReference1.modificarCandidatoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servidor.com/Conector/modificarCandidatoRequest", ReplyAction="http://servidor.com/Conector/modificarCandidatoResponse")]
        System.Threading.Tasks.Task<CandidatosWSDL.ServiceReference1.modificarCandidatoResponse> modificarCandidatoAsync(CandidatosWSDL.ServiceReference1.modificarCandidatoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://servidor.com/).
        [System.ServiceModel.OperationContractAttribute(Action="http://servidor.com/Conector/eliminarCandidatoRequest", ReplyAction="http://servidor.com/Conector/eliminarCandidatoResponse")]
        CandidatosWSDL.ServiceReference1.eliminarCandidatoResponse eliminarCandidato(CandidatosWSDL.ServiceReference1.eliminarCandidatoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servidor.com/Conector/eliminarCandidatoRequest", ReplyAction="http://servidor.com/Conector/eliminarCandidatoResponse")]
        System.Threading.Tasks.Task<CandidatosWSDL.ServiceReference1.eliminarCandidatoResponse> eliminarCandidatoAsync(CandidatosWSDL.ServiceReference1.eliminarCandidatoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarCandidatoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarCandidato", Namespace="http://servidor.com/", Order=0)]
        public CandidatosWSDL.ServiceReference1.insertarCandidatoRequestBody Body;
        
        public insertarCandidatoRequest() {
        }
        
        public insertarCandidatoRequest(CandidatosWSDL.ServiceReference1.insertarCandidatoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertarCandidatoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string claveElectoral;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string partido;
        
        public insertarCandidatoRequestBody() {
        }
        
        public insertarCandidatoRequestBody(string claveElectoral, string partido) {
            this.claveElectoral = claveElectoral;
            this.partido = partido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarCandidatoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarCandidatoResponse", Namespace="http://servidor.com/", Order=0)]
        public CandidatosWSDL.ServiceReference1.insertarCandidatoResponseBody Body;
        
        public insertarCandidatoResponse() {
        }
        
        public insertarCandidatoResponse(CandidatosWSDL.ServiceReference1.insertarCandidatoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertarCandidatoResponseBody {
        
        public insertarCandidatoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mostrarCandidatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mostrarCandidatos", Namespace="http://servidor.com/", Order=0)]
        public CandidatosWSDL.ServiceReference1.mostrarCandidatosRequestBody Body;
        
        public mostrarCandidatosRequest() {
        }
        
        public mostrarCandidatosRequest(CandidatosWSDL.ServiceReference1.mostrarCandidatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class mostrarCandidatosRequestBody {
        
        public mostrarCandidatosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mostrarCandidatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mostrarCandidatosResponse", Namespace="http://servidor.com/", Order=0)]
        public CandidatosWSDL.ServiceReference1.mostrarCandidatosResponseBody Body;
        
        public mostrarCandidatosResponse() {
        }
        
        public mostrarCandidatosResponse(CandidatosWSDL.ServiceReference1.mostrarCandidatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class mostrarCandidatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public mostrarCandidatosResponseBody() {
        }
        
        public mostrarCandidatosResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarCiudadanoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarCiudadano", Namespace="http://servidor.com/", Order=0)]
        public CandidatosWSDL.ServiceReference1.insertarCiudadanoRequestBody Body;
        
        public insertarCiudadanoRequest() {
        }
        
        public insertarCiudadanoRequest(CandidatosWSDL.ServiceReference1.insertarCiudadanoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertarCiudadanoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombreCiudadano;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apellidoPaterno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apellidoMaterno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string claveElectoral;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string domicilio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string seccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string vigencia;
        
        public insertarCiudadanoRequestBody() {
        }
        
        public insertarCiudadanoRequestBody(string nombreCiudadano, string apellidoPaterno, string apellidoMaterno, string claveElectoral, string domicilio, string seccion, string vigencia) {
            this.nombreCiudadano = nombreCiudadano;
            this.apellidoPaterno = apellidoPaterno;
            this.apellidoMaterno = apellidoMaterno;
            this.claveElectoral = claveElectoral;
            this.domicilio = domicilio;
            this.seccion = seccion;
            this.vigencia = vigencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarCiudadanoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarCiudadanoResponse", Namespace="http://servidor.com/", Order=0)]
        public CandidatosWSDL.ServiceReference1.insertarCiudadanoResponseBody Body;
        
        public insertarCiudadanoResponse() {
        }
        
        public insertarCiudadanoResponse(CandidatosWSDL.ServiceReference1.insertarCiudadanoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertarCiudadanoResponseBody {
        
        public insertarCiudadanoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class candidatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="candidatos", Namespace="http://servidor.com/", Order=0)]
        public CandidatosWSDL.ServiceReference1.candidatosRequestBody Body;
        
        public candidatosRequest() {
        }
        
        public candidatosRequest(CandidatosWSDL.ServiceReference1.candidatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class candidatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string claveElectoral;
        
        public candidatosRequestBody() {
        }
        
        public candidatosRequestBody(string claveElectoral) {
            this.claveElectoral = claveElectoral;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class candidatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="candidatosResponse", Namespace="http://servidor.com/", Order=0)]
        public CandidatosWSDL.ServiceReference1.candidatosResponseBody Body;
        
        public candidatosResponse() {
        }
        
        public candidatosResponse(CandidatosWSDL.ServiceReference1.candidatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class candidatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public candidatosResponseBody() {
        }
        
        public candidatosResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificarCandidatoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modificarCandidato", Namespace="http://servidor.com/", Order=0)]
        public CandidatosWSDL.ServiceReference1.modificarCandidatoRequestBody Body;
        
        public modificarCandidatoRequest() {
        }
        
        public modificarCandidatoRequest(CandidatosWSDL.ServiceReference1.modificarCandidatoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class modificarCandidatoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idCandidato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string partido;
        
        public modificarCandidatoRequestBody() {
        }
        
        public modificarCandidatoRequestBody(int idCandidato, string partido) {
            this.idCandidato = idCandidato;
            this.partido = partido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificarCandidatoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modificarCandidatoResponse", Namespace="http://servidor.com/", Order=0)]
        public CandidatosWSDL.ServiceReference1.modificarCandidatoResponseBody Body;
        
        public modificarCandidatoResponse() {
        }
        
        public modificarCandidatoResponse(CandidatosWSDL.ServiceReference1.modificarCandidatoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class modificarCandidatoResponseBody {
        
        public modificarCandidatoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCandidato", WrapperNamespace="http://servidor.com/", IsWrapped=true)]
    public partial class eliminarCandidatoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int idCandidato;
        
        public eliminarCandidatoRequest() {
        }
        
        public eliminarCandidatoRequest(int idCandidato) {
            this.idCandidato = idCandidato;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCandidatoResponse", WrapperNamespace="http://servidor.com/", IsWrapped=true)]
    public partial class eliminarCandidatoResponse {
        
        public eliminarCandidatoResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConectorChannel : CandidatosWSDL.ServiceReference1.Conector, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConectorClient : System.ServiceModel.ClientBase<CandidatosWSDL.ServiceReference1.Conector>, CandidatosWSDL.ServiceReference1.Conector {
        
        public ConectorClient() {
        }
        
        public ConectorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConectorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConectorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConectorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CandidatosWSDL.ServiceReference1.insertarCandidatoResponse CandidatosWSDL.ServiceReference1.Conector.insertarCandidato(CandidatosWSDL.ServiceReference1.insertarCandidatoRequest request) {
            return base.Channel.insertarCandidato(request);
        }
        
        public void insertarCandidato(string claveElectoral, string partido) {
            CandidatosWSDL.ServiceReference1.insertarCandidatoRequest inValue = new CandidatosWSDL.ServiceReference1.insertarCandidatoRequest();
            inValue.Body = new CandidatosWSDL.ServiceReference1.insertarCandidatoRequestBody();
            inValue.Body.claveElectoral = claveElectoral;
            inValue.Body.partido = partido;
            CandidatosWSDL.ServiceReference1.insertarCandidatoResponse retVal = ((CandidatosWSDL.ServiceReference1.Conector)(this)).insertarCandidato(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CandidatosWSDL.ServiceReference1.insertarCandidatoResponse> CandidatosWSDL.ServiceReference1.Conector.insertarCandidatoAsync(CandidatosWSDL.ServiceReference1.insertarCandidatoRequest request) {
            return base.Channel.insertarCandidatoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CandidatosWSDL.ServiceReference1.insertarCandidatoResponse> insertarCandidatoAsync(string claveElectoral, string partido) {
            CandidatosWSDL.ServiceReference1.insertarCandidatoRequest inValue = new CandidatosWSDL.ServiceReference1.insertarCandidatoRequest();
            inValue.Body = new CandidatosWSDL.ServiceReference1.insertarCandidatoRequestBody();
            inValue.Body.claveElectoral = claveElectoral;
            inValue.Body.partido = partido;
            return ((CandidatosWSDL.ServiceReference1.Conector)(this)).insertarCandidatoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CandidatosWSDL.ServiceReference1.mostrarCandidatosResponse CandidatosWSDL.ServiceReference1.Conector.mostrarCandidatos(CandidatosWSDL.ServiceReference1.mostrarCandidatosRequest request) {
            return base.Channel.mostrarCandidatos(request);
        }
        
        public string mostrarCandidatos() {
            CandidatosWSDL.ServiceReference1.mostrarCandidatosRequest inValue = new CandidatosWSDL.ServiceReference1.mostrarCandidatosRequest();
            inValue.Body = new CandidatosWSDL.ServiceReference1.mostrarCandidatosRequestBody();
            CandidatosWSDL.ServiceReference1.mostrarCandidatosResponse retVal = ((CandidatosWSDL.ServiceReference1.Conector)(this)).mostrarCandidatos(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CandidatosWSDL.ServiceReference1.mostrarCandidatosResponse> CandidatosWSDL.ServiceReference1.Conector.mostrarCandidatosAsync(CandidatosWSDL.ServiceReference1.mostrarCandidatosRequest request) {
            return base.Channel.mostrarCandidatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<CandidatosWSDL.ServiceReference1.mostrarCandidatosResponse> mostrarCandidatosAsync() {
            CandidatosWSDL.ServiceReference1.mostrarCandidatosRequest inValue = new CandidatosWSDL.ServiceReference1.mostrarCandidatosRequest();
            inValue.Body = new CandidatosWSDL.ServiceReference1.mostrarCandidatosRequestBody();
            return ((CandidatosWSDL.ServiceReference1.Conector)(this)).mostrarCandidatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CandidatosWSDL.ServiceReference1.insertarCiudadanoResponse CandidatosWSDL.ServiceReference1.Conector.insertarCiudadano(CandidatosWSDL.ServiceReference1.insertarCiudadanoRequest request) {
            return base.Channel.insertarCiudadano(request);
        }
        
        public void insertarCiudadano(string nombreCiudadano, string apellidoPaterno, string apellidoMaterno, string claveElectoral, string domicilio, string seccion, string vigencia) {
            CandidatosWSDL.ServiceReference1.insertarCiudadanoRequest inValue = new CandidatosWSDL.ServiceReference1.insertarCiudadanoRequest();
            inValue.Body = new CandidatosWSDL.ServiceReference1.insertarCiudadanoRequestBody();
            inValue.Body.nombreCiudadano = nombreCiudadano;
            inValue.Body.apellidoPaterno = apellidoPaterno;
            inValue.Body.apellidoMaterno = apellidoMaterno;
            inValue.Body.claveElectoral = claveElectoral;
            inValue.Body.domicilio = domicilio;
            inValue.Body.seccion = seccion;
            inValue.Body.vigencia = vigencia;
            CandidatosWSDL.ServiceReference1.insertarCiudadanoResponse retVal = ((CandidatosWSDL.ServiceReference1.Conector)(this)).insertarCiudadano(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CandidatosWSDL.ServiceReference1.insertarCiudadanoResponse> CandidatosWSDL.ServiceReference1.Conector.insertarCiudadanoAsync(CandidatosWSDL.ServiceReference1.insertarCiudadanoRequest request) {
            return base.Channel.insertarCiudadanoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CandidatosWSDL.ServiceReference1.insertarCiudadanoResponse> insertarCiudadanoAsync(string nombreCiudadano, string apellidoPaterno, string apellidoMaterno, string claveElectoral, string domicilio, string seccion, string vigencia) {
            CandidatosWSDL.ServiceReference1.insertarCiudadanoRequest inValue = new CandidatosWSDL.ServiceReference1.insertarCiudadanoRequest();
            inValue.Body = new CandidatosWSDL.ServiceReference1.insertarCiudadanoRequestBody();
            inValue.Body.nombreCiudadano = nombreCiudadano;
            inValue.Body.apellidoPaterno = apellidoPaterno;
            inValue.Body.apellidoMaterno = apellidoMaterno;
            inValue.Body.claveElectoral = claveElectoral;
            inValue.Body.domicilio = domicilio;
            inValue.Body.seccion = seccion;
            inValue.Body.vigencia = vigencia;
            return ((CandidatosWSDL.ServiceReference1.Conector)(this)).insertarCiudadanoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CandidatosWSDL.ServiceReference1.candidatosResponse CandidatosWSDL.ServiceReference1.Conector.candidatos(CandidatosWSDL.ServiceReference1.candidatosRequest request) {
            return base.Channel.candidatos(request);
        }
        
        public string candidatos(string claveElectoral) {
            CandidatosWSDL.ServiceReference1.candidatosRequest inValue = new CandidatosWSDL.ServiceReference1.candidatosRequest();
            inValue.Body = new CandidatosWSDL.ServiceReference1.candidatosRequestBody();
            inValue.Body.claveElectoral = claveElectoral;
            CandidatosWSDL.ServiceReference1.candidatosResponse retVal = ((CandidatosWSDL.ServiceReference1.Conector)(this)).candidatos(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CandidatosWSDL.ServiceReference1.candidatosResponse> CandidatosWSDL.ServiceReference1.Conector.candidatosAsync(CandidatosWSDL.ServiceReference1.candidatosRequest request) {
            return base.Channel.candidatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<CandidatosWSDL.ServiceReference1.candidatosResponse> candidatosAsync(string claveElectoral) {
            CandidatosWSDL.ServiceReference1.candidatosRequest inValue = new CandidatosWSDL.ServiceReference1.candidatosRequest();
            inValue.Body = new CandidatosWSDL.ServiceReference1.candidatosRequestBody();
            inValue.Body.claveElectoral = claveElectoral;
            return ((CandidatosWSDL.ServiceReference1.Conector)(this)).candidatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CandidatosWSDL.ServiceReference1.modificarCandidatoResponse CandidatosWSDL.ServiceReference1.Conector.modificarCandidato(CandidatosWSDL.ServiceReference1.modificarCandidatoRequest request) {
            return base.Channel.modificarCandidato(request);
        }
        
        public void modificarCandidato(int idCandidato, string partido) {
            CandidatosWSDL.ServiceReference1.modificarCandidatoRequest inValue = new CandidatosWSDL.ServiceReference1.modificarCandidatoRequest();
            inValue.Body = new CandidatosWSDL.ServiceReference1.modificarCandidatoRequestBody();
            inValue.Body.idCandidato = idCandidato;
            inValue.Body.partido = partido;
            CandidatosWSDL.ServiceReference1.modificarCandidatoResponse retVal = ((CandidatosWSDL.ServiceReference1.Conector)(this)).modificarCandidato(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CandidatosWSDL.ServiceReference1.modificarCandidatoResponse> CandidatosWSDL.ServiceReference1.Conector.modificarCandidatoAsync(CandidatosWSDL.ServiceReference1.modificarCandidatoRequest request) {
            return base.Channel.modificarCandidatoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CandidatosWSDL.ServiceReference1.modificarCandidatoResponse> modificarCandidatoAsync(int idCandidato, string partido) {
            CandidatosWSDL.ServiceReference1.modificarCandidatoRequest inValue = new CandidatosWSDL.ServiceReference1.modificarCandidatoRequest();
            inValue.Body = new CandidatosWSDL.ServiceReference1.modificarCandidatoRequestBody();
            inValue.Body.idCandidato = idCandidato;
            inValue.Body.partido = partido;
            return ((CandidatosWSDL.ServiceReference1.Conector)(this)).modificarCandidatoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CandidatosWSDL.ServiceReference1.eliminarCandidatoResponse CandidatosWSDL.ServiceReference1.Conector.eliminarCandidato(CandidatosWSDL.ServiceReference1.eliminarCandidatoRequest request) {
            return base.Channel.eliminarCandidato(request);
        }
        
        public void eliminarCandidato(int idCandidato) {
            CandidatosWSDL.ServiceReference1.eliminarCandidatoRequest inValue = new CandidatosWSDL.ServiceReference1.eliminarCandidatoRequest();
            inValue.idCandidato = idCandidato;
            CandidatosWSDL.ServiceReference1.eliminarCandidatoResponse retVal = ((CandidatosWSDL.ServiceReference1.Conector)(this)).eliminarCandidato(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CandidatosWSDL.ServiceReference1.eliminarCandidatoResponse> CandidatosWSDL.ServiceReference1.Conector.eliminarCandidatoAsync(CandidatosWSDL.ServiceReference1.eliminarCandidatoRequest request) {
            return base.Channel.eliminarCandidatoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CandidatosWSDL.ServiceReference1.eliminarCandidatoResponse> eliminarCandidatoAsync(int idCandidato) {
            CandidatosWSDL.ServiceReference1.eliminarCandidatoRequest inValue = new CandidatosWSDL.ServiceReference1.eliminarCandidatoRequest();
            inValue.idCandidato = idCandidato;
            return ((CandidatosWSDL.ServiceReference1.Conector)(this)).eliminarCandidatoAsync(inValue);
        }
    }
}
